services:
  - type: web
    name: maven-ai-backend
    runtime: ruby
    buildCommand: bundle install
    startCommand: bundle exec rails server -b 0.0.0.0 -p $PORT
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: OPENAI_ACCESS_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: maven-ai-db
          property: connectionString
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-1
      - key: AWS_BUCKET_NAME
        sync: false

databases:
  - name: maven-ai-db
    databaseName: maven_ai_production
    plan: free
